version: "3"
services:
  db:
    container_name: challenge_db
    build: ./postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    container_name: challenge_api
    build: ./api
    environment:
      PORT: ${PORT}
      NODE_ENV: production
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  ui:
    container_name: challenge_ui
    build: ./ui
    ports:
      - "3001:3001"
volumes:
  db:
    external: true
